-- ============================================================
-- V1 · users 表初始 schema（user-service 唯一数据权威）
--
-- 设计依据：
--   - DATA_GOVERNANCE.md §4.1 命名规范（snake_case / 复数表名 / _at 后缀）
--   - ADR-0021（Flyway 数据库迁移 · Phase 6）
--
-- 注意：
--   - 本迁移是「纯 CREATE」，假设空库或 Flyway 管理下的库。
--   - 若旧库存在 Hibernate ddl-auto=update 自动建的 users 表，
--     需先一次性 DROP（见 .ai/conversations/2026-01-22-flyway-schema.md）。
-- ============================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    display_name  VARCHAR(128) NOT NULL,
    email         VARCHAR(254),
    phone         VARCHAR(20),
    password_hash VARCHAR(100) NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    roles         TEXT[]       NOT NULL DEFAULT ARRAY['USER'],
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED'))
);

COMMENT ON TABLE users IS '用户主数据（user-service 唯一持有，见 DATA_GOVERNANCE.md §1）';
COMMENT ON COLUMN users.id IS '自增主键（IDENTITY）';
COMMENT ON COLUMN users.username IS '登录名，唯一';
COMMENT ON COLUMN users.display_name IS '显示名（必填）';
COMMENT ON COLUMN users.email IS '邮箱（可选，唯一；NULL 不参与唯一约束）';
COMMENT ON COLUMN users.phone IS '手机号（可选）';
COMMENT ON COLUMN users.password_hash IS 'BCrypt 哈希，绝不出现在公开端点';
COMMENT ON COLUMN users.status IS '账户状态：ACTIVE / DISABLED / LOCKED';
COMMENT ON COLUMN users.roles IS '角色数组（TEXT[]），默认 USER；RBAC 后续演进为独立表';
COMMENT ON COLUMN users.created_at IS '创建时间（服务端赋默认值）';
COMMENT ON COLUMN users.updated_at IS '最后更新时间（应用层 @PreUpdate 维护）';
COMMENT ON COLUMN users.last_login_at IS '最近一次登录时间（auth-service 登录成功后回写）';
