-- ============================================================
-- V2 · 多租户：tenants 表 + users.tenant_id（ADR-0022）
--
-- 方案：共享表 + tenant_id 行级隔离 + 应用层强制过滤。
--   - 新表 tenants（企业/租户），code 唯一（登录用）
--   - users.tenant_id NOT NULL → 归属租户
--   - 唯一约束：uk_users_username（全局）→ uk_users_tenant_username（租户内）
--   - seed：默认租户「猎手猫」（code=huntercat），存量用户归入
-- ============================================================

CREATE TABLE tenants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(128) NOT NULL,
    code       VARCHAR(64)  NOT NULL,
    status     VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_tenants_code UNIQUE (code),
    CONSTRAINT ck_tenants_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

COMMENT ON TABLE tenants IS '租户（企业/组织）；多租户共享表 + tenant_id 行级隔离（ADR-0022）';
COMMENT ON COLUMN tenants.code IS '租户编码，登录时标识（如 huntercat / zhiye），唯一';
COMMENT ON COLUMN tenants.status IS '租户状态：ACTIVE / DISABLED';

-- seed：默认租户「猎手猫」（公司自身，第一个真实租户）
INSERT INTO tenants (name, code)
VALUES ('南昌猎手猫数字科技有限公司', 'huntercat');

-- users 加租户维度（先可空再回填，避免默认值污染未来插入）
ALTER TABLE users ADD COLUMN tenant_id BIGINT;
UPDATE users SET tenant_id = 1 WHERE tenant_id IS NULL;
ALTER TABLE users ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

-- username 唯一性从全局改为「租户内唯一」
ALTER TABLE users DROP CONSTRAINT uk_users_username;
ALTER TABLE users ADD CONSTRAINT uk_users_tenant_username UNIQUE (tenant_id, username);

CREATE INDEX idx_users_tenant_id ON users (tenant_id);

COMMENT ON COLUMN users.tenant_id IS '归属租户（FK → tenants.id）；新建用户必须显式提供';
