-- ============================================================
-- V3 · 认证体系扩展：验证码存储 + users.phone 唯一（ADR-0023）
--
--   - verification_codes：短信/邮箱验证码（登录/注册/重置密码）
--   - users.phone 全局唯一（可空；NULL 不参与唯一约束）
--     —— 手机号全局唯一（一个手机号一个账号），验证码登录按 phone 查
-- ============================================================

CREATE TABLE verification_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel    VARCHAR(16)  NOT NULL,
    target     VARCHAR(254) NOT NULL,
    purpose    VARCHAR(16)  NOT NULL,
    code       VARCHAR(10)  NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_vc_channel CHECK (channel IN ('SMS', 'EMAIL')),
    CONSTRAINT ck_vc_purpose CHECK (purpose IN ('LOGIN', 'REGISTER', 'RESET_PASSWORD'))
);

COMMENT ON TABLE verification_codes IS '验证码（短信/邮箱；登录/注册/重置密码）· ADR-0023';
COMMENT ON COLUMN verification_codes.channel IS '渠道：SMS / EMAIL';
COMMENT ON COLUMN verification_codes.target IS '接收方：手机号或邮箱';
COMMENT ON COLUMN verification_codes.purpose IS '用途：LOGIN / REGISTER / RESET_PASSWORD';
COMMENT ON COLUMN verification_codes.code IS '6 位数字验证码';
COMMENT ON COLUMN verification_codes.expires_at IS '过期时间';
COMMENT ON COLUMN verification_codes.used_at IS '使用时间（一次性）';

CREATE INDEX idx_vc_target_purpose ON verification_codes (target, purpose, channel);

-- 手机号全局唯一（一个手机号一个账号；可空，NULL 不参与唯一约束）
ALTER TABLE users ADD CONSTRAINT uk_users_phone UNIQUE (phone);

COMMENT ON COLUMN users.phone IS '手机号（全局唯一，可空；验证码登录按此查用户）';
