-- ============================================================
-- V4 · 邀请注册：tenant_invites 表（ADR-0023 Phase 2）
--
--   租户管理员生成邀请码 → 受邀人注册时填邀请码 → 自动加入该租户并分配角色
--   - code 唯一（8 位随机大写）
--   - expires_at 可空（不设则永不过期）
--   - max_uses 可空（不设则无限次），used_count 计数
--   - revoked_at 撤销标记（软撤销）
-- ============================================================

CREATE TABLE tenant_invites (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT NOT NULL,
    code       VARCHAR(32) NOT NULL,
    role       VARCHAR(16) NOT NULL DEFAULT 'USER',
    expires_at TIMESTAMPTZ,
    max_uses   INT,
    used_count INT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ,
    CONSTRAINT fk_invites_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT uk_tenant_invites_code UNIQUE (code),
    CONSTRAINT ck_tenant_invites_role CHECK (role IN ('USER', 'ADMIN'))
);

COMMENT ON TABLE tenant_invites IS '邀请码（ADR-0023 Phase 2）：受邀人注册自动入租户';
COMMENT ON COLUMN tenant_invites.code IS '邀请码（唯一）';
COMMENT ON COLUMN tenant_invites.role IS '受邀人角色：USER / ADMIN';
COMMENT ON COLUMN tenant_invites.expires_at IS '过期时间（空 = 永不过期）';
COMMENT ON COLUMN tenant_invites.max_uses IS '最大使用次数（空 = 无限）';
COMMENT ON COLUMN tenant_invites.used_count IS '已使用次数';
COMMENT ON COLUMN tenant_invites.revoked_at IS '撤销时间（软撤销）';

CREATE INDEX idx_tenant_invites_tenant ON tenant_invites (tenant_id);
