-- ============================================================
-- V5 · RBAC：roles + user_roles 表（替换 users.roles TEXT[] 数组）
--
--   - roles：角色定义（PLATFORM / TENANT 两级 scope）
--   - user_roles：用户-角色关联（多对多）
--   - 迁移：users.roles 数组 → user_roles（USER→USER，ADMIN→TENANT_ADMIN）
--   - 移除 users.roles 冗余列（统一 user_roles 权威）
-- ============================================================

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(32)  NOT NULL,
    name        VARCHAR(64)  NOT NULL,
    scope       VARCHAR(16)  NOT NULL DEFAULT 'TENANT',
    description VARCHAR(255),
    is_system   BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_roles_code UNIQUE (code),
    CONSTRAINT ck_roles_scope CHECK (scope IN ('PLATFORM', 'TENANT'))
);

COMMENT ON TABLE roles IS '角色定义（RBAC · ADR-0024）';
COMMENT ON COLUMN roles.scope IS '范围：PLATFORM（平台运营）/ TENANT（租户内）';
COMMENT ON COLUMN roles.is_system IS '系统内置角色（不可删除）';

-- seed：系统内置三角色
INSERT INTO roles (code, name, scope, description, is_system) VALUES
  ('PLATFORM_ADMIN', '平台管理员', 'PLATFORM', '跨租户运营管理（租户/角色/全量用户）', true),
  ('TENANT_ADMIN',   '租户管理员', 'TENANT',   '管理本租户用户与邀请', true),
  ('USER',           '普通用户',   'TENANT',   '基础使用', true);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

COMMENT ON TABLE user_roles IS '用户-角色关联（RBAC · ADR-0024）';

-- 迁移存量 users.roles 数组 → user_roles（USER→USER，ADMIN→TENANT_ADMIN）
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
CROSS JOIN LATERAL unnest(u.roles) AS ur(role)
JOIN roles r ON r.code = CASE ur.role WHEN 'ADMIN' THEN 'TENANT_ADMIN' ELSE 'USER' END;

-- roles 数组不再权威，移除冗余列
ALTER TABLE users DROP COLUMN roles;

CREATE INDEX idx_user_roles_role ON user_roles (role_id);
