-- ============================================================
-- V6 · audit_logs 操作审计表（DATA_SECURITY.md §7 审计日志）
--
-- 六要素（who / when / what / from / outcome / request_id）：
--   who        user_id（gateway 从 JWT 注入 X-User-Id）
--   when       created_at（UTC，服务端默认 now()）
--   what       resource_type + resource_id + action + detail
--   from       source_ip + user_agent
--   outcome    SUCCESS / DENIED / ERROR
--   request_id 可追溯（gateway 透传 X-Request-Id，可为空）
--
-- 只写不改不删（append-only）：审计日志不可更新/删除（连平台管理员也不行），
-- 保留期见 DATA_SECURITY.md §5.2（操作审计 3-7 年）。
-- ============================================================

CREATE TABLE audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT,                              -- 操作作用域租户（平台操作 = 操作者租户）
    user_id       BIGINT,                              -- 操作者（who）
    action        VARCHAR(16)  NOT NULL,               -- CREATE / UPDATE / DELETE / DENIED / LOGIN / READ
    resource_type VARCHAR(32)  NOT NULL,               -- USER / TENANT / ROLE / ...
    resource_id   BIGINT,                              -- 被操作资源 id
    detail        VARCHAR(500),                        -- 摘要（如 "删除用户 zhangsan"）
    source_ip     VARCHAR(64),                         -- from：X-Forwarded-For / remoteAddr
    user_agent    VARCHAR(255),                        -- from
    outcome       VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS', -- SUCCESS / DENIED / ERROR
    request_id    VARCHAR(64),                         -- gateway 透传（可为空）
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(), -- when（UTC）
    CONSTRAINT ck_audit_logs_action CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'DENIED', 'LOGIN', 'READ')),
    CONSTRAINT ck_audit_logs_outcome CHECK (outcome IN ('SUCCESS', 'DENIED', 'ERROR'))
);

CREATE INDEX idx_audit_logs_tenant_created ON audit_logs (tenant_id, created_at DESC);
CREATE INDEX idx_audit_logs_resource ON audit_logs (resource_type, resource_id);

COMMENT ON TABLE audit_logs IS '操作审计（append-only · DATA_SECURITY §7）';
COMMENT ON COLUMN audit_logs.tenant_id IS '作用域租户：租户内操作=该租户；平台操作（租户/角色管理）=操作者所在租户';
COMMENT ON COLUMN audit_logs.outcome IS 'SUCCESS 成功 / DENIED 拒绝（越权等）/ ERROR 失败';
